FROM node:20 AS build-stage 
WORKDIR /usr/src/app
COPY . .
RUN npm ci
RUN npm run build

FROM build-stage AS test
ENV NODE_ENV test
RUN npm run test

FROM nginx:1.25-alpine
COPY --from=build-stage /usr/src/app/dist /usr/share/nginx/html